# Generated by Django 4.2 on 2025-12-17 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cust",
            fields=[
                (
                    "cust_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("email", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=1000)),
                (
                    "last_login",
                    models.CharField(
                        blank=True, db_column="last_login_dt", max_length=14, null=True
                    ),
                ),
                ("created_dt", models.CharField(max_length=8)),
                ("updated_dt", models.CharField(blank=True, max_length=8, null=True)),
                ("leave_dt", models.CharField(blank=True, max_length=8, null=True)),
                ("retry_cnt", models.IntegerField(default=0)),
                ("lock_yn", models.CharField(default="N", max_length=1)),
            ],
            options={
                "db_table": "CUST_TM",
            },
        ),
        migrations.CreateModel(
            name="CusProfile",
            fields=[
                (
                    "cust",
                    models.OneToOneField(
                        db_column="cust_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="accounts.cust",
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "bmr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("gender", models.CharField(blank=True, max_length=1, null=True)),
                ("birth_dt", models.CharField(blank=True, max_length=8, null=True)),
                ("ratio_carb", models.IntegerField(blank=True, null=True)),
                ("ratio_protein", models.IntegerField(blank=True, null=True)),
                ("ratio_fat", models.IntegerField(blank=True, null=True)),
                (
                    "activity_level",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("purpose", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "calories_burned",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "recommended_calories",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("offset", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "CUS_PROFILE_TS",
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("login_dt", models.CharField(max_length=8)),
                ("seq", models.BigIntegerField()),
                ("login_time", models.CharField(max_length=14)),
                ("logout_time", models.CharField(blank=True, max_length=14, null=True)),
                ("success_yn", models.CharField(max_length=1)),
                (
                    "cust",
                    models.ForeignKey(
                        db_column="cust_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.cust",
                    ),
                ),
            ],
            options={
                "db_table": "login_th",
                "unique_together": {("cust", "login_dt", "seq")},
            },
        ),
    ]
