# Generated by Django 4.2 on 2025-12-17 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cust",
            fields=[
                (
                    "cust_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("email", models.CharField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=1000)),
                ("created_dt", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "last_login",
                    models.CharField(
                        blank=True, db_column="last_login_dt", max_length=8, null=True
                    ),
                ),
                ("updated_dt", models.CharField(blank=True, max_length=8, null=True)),
                ("leave_dt", models.CharField(blank=True, max_length=8, null=True)),
                ("retry_cnt", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "lock_yn",
                    models.CharField(blank=True, default="N", max_length=1, null=True),
                ),
                (
                    "created_time",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                (
                    "updated_time",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
            ],
            options={
                "db_table": "CUST_TM",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CusProfile",
            fields=[
                (
                    "cust",
                    models.OneToOneField(
                        db_column="cust_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "weight_kg",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "bmi",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "bmr",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("gender", models.CharField(max_length=1, null=True)),
                ("birth_dt", models.CharField(max_length=8, null=True)),
                ("ratio_carb", models.IntegerField(db_column="Ratio_carb", null=True)),
                (
                    "ratio_protein",
                    models.IntegerField(db_column="Ratio_protein", null=True),
                ),
                ("ratio_fat", models.IntegerField(db_column="Ratio_fat", null=True)),
                ("activity_level", models.CharField(max_length=1, null=True)),
                ("purpose", models.CharField(max_length=1, null=True)),
                (
                    "calories_burned",
                    models.DecimalField(
                        db_column="Calories_burned",
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "recommended_calories",
                    models.DecimalField(
                        db_column="Recommended_calories",
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                    ),
                ),
                ("offset", models.FloatField(db_column="Offset", null=True)),
                ("created_time", models.CharField(max_length=14, null=True)),
                ("updated_time", models.CharField(max_length=14, null=True)),
            ],
            options={
                "db_table": "CUS_PROFILE_TS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "cust",
                    models.ForeignKey(
                        db_column="cust_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("login_dt", models.CharField(max_length=8)),
                ("seq", models.BigIntegerField()),
                ("login_time", models.CharField(blank=True, max_length=14, null=True)),
                ("logout_time", models.CharField(blank=True, max_length=14, null=True)),
                ("success_yn", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "created_time",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                (
                    "updated_time",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
            ],
            options={
                "db_table": "LOGIN_TH",
                "managed": False,
            },
        ),
    ]
