# Generated by Django 4.2 on 2025-12-17 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cusprofile",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="cust",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="loginhistory",
            options={"managed": False},
        ),
    ]
