"""
Django settings for conf project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# 로컬에서만 .env를 읽고 싶다면 (권장)
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / ".env")
except Exception:
    pass


# =========================
# Environment / Core
# =========================

SECRET_KEY = os.environ.get("SECRET_KEY", "")
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY is missing (check EB .env vars or ..env quoting).")

DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() in ("true", "1", "yes")


# EB 도메인(환경변수로 오버라이드 가능)
EB_DOMAIN = os.environ.get(
    "EB_DOMAIN",
    "bear-app-.env.eba-temmzk66.ap-northeast-2.elasticbeanstalk.com",
)

# ALLOWED_HOSTS="*.elasticbeanstalk.com,localhost,127.0.0.1" 처럼 넣는다고 가정

ALLOWED_HOSTS_RAW = os.environ.get("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS_RAW.split(",") if h.strip()]

# =========================
# Application definition
# =========================

INSTALLED_APPS = [
    "api",
    "ml",
    "record",
    "settings",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts.apps.AccountsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "conf.middleware.DemoModeBlockMiddleware",
]

ROOT_URLCONF = "conf.urls"

TEMPLATES_DIR = BASE_DIR / "templates"
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATES_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "conf.wsgi.application"


# =========================
# Database
# =========================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("DB_NAME", ""),
        "USER": os.environ.get("DB_USER", ""),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", ""),
        "PORT": os.environ.get("DB_PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

required_env = ["DB_HOST", "DB_NAME", "DB_USER", "DB_PASSWORD", "SECRET_KEY"]
missing = [k for k in required_env if not os.environ.get(k)]
if missing:
    # 환경변수 누락이면 배포 시 즉시 터지므로, EB 콘솔에서 반드시 설정해줘야 함
    raise RuntimeError(f"Missing required ..env vars: {', '.join(missing)}")


# =========================
# Auth
# =========================
CSRF_FAILURE_VIEW = "conf.views.csrf_failure"


AUTHENTICATION_BACKENDS = [
    "accounts.backends.CustBackend",  # 커스텀 backend
    "django.contrib.auth.backends.ModelBackend",  # Django 기본 backend
]

AUTH_USER_MODEL = "accounts.Cust"

# 로그인/로그아웃 URL 정책 (named url로 통일)
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

LOGIN_URL = "root"

# =========================
# Password validation
# =========================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# =========================
# Internationalization
# =========================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Seoul"
USE_I18N = True
USE_TZ = True


# =========================
# Static files (WhiteNoise)
# =========================

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# =========================
# Default primary key field type
# =========================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =========================
# Session
# =========================

SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = True


# =========================
# Security / Proxy (Elastic Beanstalk)
# =========================

# CSRF: 반드시 scheme 포함
CSRF_TRUSTED_ORIGINS = [
    f"http://{EB_DOMAIN}",
    f"https://{EB_DOMAIN}",
    "https://d26gla0lxi34pu.cloudfront.net",
]

# Reverse proxy 뒤에서 https 인식 보정
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# 처음엔 루프 방지 위해 False 유지
SECURE_SSL_REDIRECT = False

# =========================
# Email (SMTP)
# =========================
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True").lower() in ("true", "1", "yes")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@bear.local"
)
EMAIL_FAIL_SILENTLY = os.environ.get("EMAIL_FAIL_SILENTLY", "False").lower() in (
    "true",
    "1",
    "yes",
)

# =========================
# Password Reset
# =========================
# 토큰 유효시간(초). 기본값도 있지만 명시해두면 운영에서 편함.
# 60 * 60 * 24 = 1 day
PASSWORD_RESET_TIMEOUT = int(
    os.environ.get("PASSWORD_RESET_TIMEOUT", str(60 * 60 * 24))
)
